services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppoloDev\UIToolboxBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'


